import type { NextPage } from "next";
import Head from "next/head";
import { BibleBooks } from "../components/Books";
import { Contents } from "../components/Contents";
import { Books } from "../data";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto px-4">
        <header className="fixed z-10 bg-white w-full py-2 flex justify-between items-center left-0 right-0 px-4">
          <div>
            <h1 className="text-4xl text-slate-800 m-0">
              <a href="#home">Pocket Bible</a>
            </h1>
            <em className="flex text-slate-400 text-sm">
              Selected Verses from Good News Bible
            </em>
          </div>
          <div>
            <a
              href="#home"
              title="Back to Book List"
              className="underline-offset-2 underline text-slate-400"
            >
              Contents
            </a>
          </div>
        </header>
        {/* This would a component that gets rendered in the loop of books */}
        <div>
          <Contents Books={Books} />
          <BibleBooks Books={Books} />
        </div>
      </main>
    </div>
  );
};

export default Home;
